/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Permicoes.java
 *
 * Created on Sep 12, 2015, 8:44:48 PM
 */
package interfaces;

import javax.swing.JCheckBox;

/**
 *
 * @author ILIDIOP
 */
public class Permicoes extends javax.swing.JPanel {

    /** Creates new form Permicoes */
    public Permicoes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cFornecedor = new javax.swing.JCheckBox();
        cCadastrarF = new javax.swing.JCheckBox();
        cRemoverF = new javax.swing.JCheckBox();
        cAlterarC = new javax.swing.JCheckBox();
        cremoverC = new javax.swing.JCheckBox();
        cCadastrarC = new javax.swing.JCheckBox();
        cCliente = new javax.swing.JCheckBox();
        cAlterarF = new javax.swing.JCheckBox();
        cVendas = new javax.swing.JCheckBox();
        cFazerVendas = new javax.swing.JCheckBox();
        cFazerPedidos = new javax.swing.JCheckBox();
        cFazerCotacao = new javax.swing.JCheckBox();
        cDefinirDesconto = new javax.swing.JCheckBox();
        cUsuario = new javax.swing.JCheckBox();
        cCadastrarU = new javax.swing.JCheckBox();
        cRemoverU = new javax.swing.JCheckBox();
        cAlterarU = new javax.swing.JCheckBox();
        cRelatorios = new javax.swing.JCheckBox();
        cREntradaP = new javax.swing.JCheckBox();
        cSaidaP = new javax.swing.JCheckBox();
        cREstoque = new javax.swing.JCheckBox();
        cRPrazo = new javax.swing.JCheckBox();
        cProdutos = new javax.swing.JCheckBox();
        cRemoverP = new javax.swing.JCheckBox();
        cAlterarP = new javax.swing.JCheckBox();
        cCadastrarP = new javax.swing.JCheckBox();

        cFornecedor.setFont(new java.awt.Font("Serif", 1, 14));
        cFornecedor.setText("Fornecedors");
        cFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFornecedorActionPerformed(evt);
            }
        });

        cCadastrarF.setFont(new java.awt.Font("Serif", 0, 14));
        cCadastrarF.setText("Permitir o  usuario a cadastrar o fornecedor");
        cCadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCadastrarFActionPerformed(evt);
            }
        });

        cRemoverF.setFont(new java.awt.Font("Serif", 0, 14));
        cRemoverF.setText("Permitir o  usuario a remover  o fornecedor");

        cAlterarC.setFont(new java.awt.Font("Serif", 0, 14));
        cAlterarC.setText("Permitir o  usuario a alterar um cliente");

        cremoverC.setFont(new java.awt.Font("Serif", 0, 14));
        cremoverC.setText("Permitir o  usuario a remover cliente");
        cremoverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cremoverCActionPerformed(evt);
            }
        });

        cCadastrarC.setFont(new java.awt.Font("Serif", 0, 14));
        cCadastrarC.setText("Permitir o  usuario a cadastrar o cliente");
        cCadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCadastrarCActionPerformed(evt);
            }
        });

        cCliente.setFont(new java.awt.Font("Serif", 1, 14));
        cCliente.setText("Clientes");
        cCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cClienteActionPerformed(evt);
            }
        });

        cAlterarF.setFont(new java.awt.Font("Serif", 0, 14));
        cAlterarF.setText("Permitir o  usuario a alterar um fornecedor");

        cVendas.setFont(new java.awt.Font("Serif", 1, 14));
        cVendas.setText("Vendas");
        cVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVendasActionPerformed(evt);
            }
        });

        cFazerVendas.setFont(new java.awt.Font("Serif", 0, 14));
        cFazerVendas.setText("Permitir o  usuario a efetuar venda");
        cFazerVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFazerVendasActionPerformed(evt);
            }
        });

        cFazerPedidos.setFont(new java.awt.Font("Serif", 0, 14));
        cFazerPedidos.setText("Permitir o  usuario a efetuar pedidos");

        cFazerCotacao.setFont(new java.awt.Font("Serif", 0, 14));
        cFazerCotacao.setText("Permitir o  usuario fazer cotacao");

        cDefinirDesconto.setFont(new java.awt.Font("Serif", 0, 14));
        cDefinirDesconto.setText("Permitir o  usuario definir descontos");

        cUsuario.setFont(new java.awt.Font("Serif", 1, 14));
        cUsuario.setText("Usuarios");
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });

        cCadastrarU.setFont(new java.awt.Font("Serif", 0, 14));
        cCadastrarU.setText("Permitir o  usuario a cadastrar outos usuarios");

        cRemoverU.setFont(new java.awt.Font("Serif", 0, 14));
        cRemoverU.setText("Permitir o  usuario a remover outros usuarios");

        cAlterarU.setFont(new java.awt.Font("Serif", 0, 14));
        cAlterarU.setText("Permitir o  usuario a alterar outros usuarios");

        cRelatorios.setFont(new java.awt.Font("Serif", 1, 14));
        cRelatorios.setText("Relatorios");
        cRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRelatoriosActionPerformed(evt);
            }
        });

        cREntradaP.setFont(new java.awt.Font("Serif", 0, 14));
        cREntradaP.setText("Aceder relatorio de entrada de produtos");
        cREntradaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cREntradaPActionPerformed(evt);
            }
        });

        cSaidaP.setFont(new java.awt.Font("Serif", 0, 14));
        cSaidaP.setText("Aceder relatorio de saida de produtos");
        cSaidaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSaidaPActionPerformed(evt);
            }
        });

        cREstoque.setFont(new java.awt.Font("Serif", 0, 14));
        cREstoque.setText("Aceder relatorio de produtos abaicho de estoque");

        cRPrazo.setFont(new java.awt.Font("Serif", 0, 14));
        cRPrazo.setText("Aceder relatorio de produtos prestes a aspirar o praso");

        cProdutos.setFont(new java.awt.Font("Serif", 1, 14));
        cProdutos.setText("Produtos");
        cProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProdutosActionPerformed(evt);
            }
        });

        cRemoverP.setFont(new java.awt.Font("Serif", 0, 14));
        cRemoverP.setText("Permitir o  usuario a remover um produto");

        cAlterarP.setFont(new java.awt.Font("Serif", 0, 14));
        cAlterarP.setText("Permitir o  usuario a alterar um produto");

        cCadastrarP.setFont(new java.awt.Font("Serif", 0, 14));
        cCadastrarP.setText("Permitir o  usuario a cadastrar o produto");
        cCadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCadastrarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cVendas)
                    .addComponent(cCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cRemoverP)
                            .addComponent(cCadastrarP)
                            .addComponent(cAlterarP)))
                    .addComponent(cProdutos)
                    .addComponent(cFornecedor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cRemoverF)
                            .addComponent(cCadastrarF)
                            .addComponent(cAlterarF)))
                    .addComponent(cRelatorios)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cremoverC)
                            .addComponent(cCadastrarC)
                            .addComponent(cAlterarC)))
                    .addComponent(cUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cCadastrarU)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cAlterarU)
                                .addComponent(cRemoverU)
                                .addComponent(cFazerPedidos)
                                .addComponent(cFazerVendas)
                                .addComponent(cFazerCotacao)
                                .addComponent(cDefinirDesconto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cSaidaP)
                            .addComponent(cREstoque)
                            .addComponent(cREntradaP)
                            .addComponent(cRPrazo))))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCadastrarF)
                .addGap(3, 3, 3)
                .addComponent(cRemoverF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cAlterarF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCadastrarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRemoverP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAlterarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCliente)
                .addGap(3, 3, 3)
                .addComponent(cCadastrarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cremoverC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cAlterarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCadastrarU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRemoverU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAlterarU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cVendas)
                .addGap(6, 6, 6)
                .addComponent(cFazerVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cFazerPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cFazerCotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cDefinirDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cREntradaP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cSaidaP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cREstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cRPrazo)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        cFornecedor.getAccessibleContext().setAccessibleName("");
        cCadastrarF.getAccessibleContext().setAccessibleName("");
        cRemoverF.getAccessibleContext().setAccessibleName("");
        cAlterarC.getAccessibleContext().setAccessibleName("");
        cremoverC.getAccessibleContext().setAccessibleName("");
        cCadastrarC.getAccessibleContext().setAccessibleName("");
        cCliente.getAccessibleContext().setAccessibleName("");
        cAlterarF.getAccessibleContext().setAccessibleName("");
        cVendas.getAccessibleContext().setAccessibleName("");
        cFazerVendas.getAccessibleContext().setAccessibleName("");
        cFazerPedidos.getAccessibleContext().setAccessibleName("");
        cFazerCotacao.getAccessibleContext().setAccessibleName("");
        cDefinirDesconto.getAccessibleContext().setAccessibleName("");
        cUsuario.getAccessibleContext().setAccessibleName("");
        cCadastrarU.getAccessibleContext().setAccessibleName("");
        cRemoverU.getAccessibleContext().setAccessibleName("");
        cAlterarU.getAccessibleContext().setAccessibleName("");
        cRelatorios.getAccessibleContext().setAccessibleName("");
        cREntradaP.getAccessibleContext().setAccessibleName("");
        cSaidaP.getAccessibleContext().setAccessibleName("");
        cREstoque.getAccessibleContext().setAccessibleName("");
        cRPrazo.getAccessibleContext().setAccessibleName("");
        cProdutos.getAccessibleContext().setAccessibleName("");
        cRemoverP.getAccessibleContext().setAccessibleName("");
        cAlterarP.getAccessibleContext().setAccessibleName("");
        cCadastrarP.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void cremoverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cremoverCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cremoverCActionPerformed

    private void cFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFornecedorActionPerformed
        if (cFornecedor.isSelected()) {
            cAlterarF.setSelected(true);
            cCadastrarF.setSelected(true);
            cRemoverF.setSelected(true);
        } else {
            cAlterarF.setSelected(false);
            cCadastrarF.setSelected(false);
            cRemoverF.setSelected(false);
        }
    }//GEN-LAST:event_cFornecedorActionPerformed

    private void cCadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCadastrarFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCadastrarFActionPerformed

    private void cClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cClienteActionPerformed
        if (cCliente.isSelected()) {
            cCadastrarC.setSelected(true);
            cAlterarC.setSelected(true);
            cremoverC.setSelected(true);
        } else {
            cCadastrarC.setSelected(false);
            cAlterarC.setSelected(false);
            cremoverC.setSelected(false);
        }
    }//GEN-LAST:event_cClienteActionPerformed

    private void cSaidaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSaidaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSaidaPActionPerformed

    private void cProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProdutosActionPerformed
        if (cProdutos.isSelected()) {
            cAlterarP.setSelected(true);
            cCadastrarP.setSelected(true);
            cRemoverP.setSelected(true);
        } else {
            cAlterarP.setSelected(false);
            cCadastrarP.setSelected(false);
            cRemoverP.setSelected(false);
        }
    }//GEN-LAST:event_cProdutosActionPerformed

    private void cRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRelatoriosActionPerformed
        if (cRelatorios.isSelected()) {
            cREntradaP.setSelected(true);
            cRPrazo.setSelected(true);
            cREstoque.setSelected(true);
            cSaidaP.setSelected(true);
        } else {
            cREntradaP.setSelected(false);
            cRPrazo.setSelected(false);
            cREstoque.setSelected(false);
            cSaidaP.setSelected(false);
        }


    }//GEN-LAST:event_cRelatoriosActionPerformed

    private void cCadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCadastrarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCadastrarCActionPerformed

    private void cFazerVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFazerVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cFazerVendasActionPerformed

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        if (cUsuario.isSelected()) {
            cCadastrarU.setSelected(true);
            cRemoverU.setSelected(true);
            cAlterarU.setSelected(true);
        } else {
            cCadastrarU.setSelected(false);
            cRemoverU.setSelected(false);
            cAlterarU.setSelected(false);
        }
    }//GEN-LAST:event_cUsuarioActionPerformed

    private void cVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVendasActionPerformed
        if (cVendas.isSelected()) {
            cFazerVendas.setSelected(true);
            cFazerCotacao.setSelected(true);
            cFazerCotacao.setSelected(true);
            cFazerPedidos.setSelected(true);
            cDefinirDesconto.setSelected(true);
        } else {
            cFazerCotacao.setSelected(false);
            cFazerCotacao.setSelected(false);
            cFazerPedidos.setSelected(false);
            cDefinirDesconto.setSelected(false);
            cFazerVendas.setSelected(false);
        }
    }//GEN-LAST:event_cVendasActionPerformed

    private void cCadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCadastrarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCadastrarPActionPerformed

    private void cREntradaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cREntradaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cREntradaPActionPerformed

    public void reiniciar() {
        if (cFornecedor.isSelected()) 
            cFornecedor.setSelected(false);
        
        if (cProdutos.isSelected()) 
            cProdutos.setSelected(false);
        
        if (cCliente.isSelected()) 
            cCliente.setSelected(false);
        
        if (cUsuario.isSelected()) 
            cUsuario.setSelected(false);
        
        if (cVendas.isSelected()) 
            cVendas.setSelected(false);
        
        if (cRelatorios.isSelected()) 
            cRelatorios.setSelected(false);
        
    }

    public JCheckBox getcAlterarC() {
        return cAlterarC;
    }

    public JCheckBox getcAlterarF() {
        return cAlterarF;
    }

    public JCheckBox getcAlterarP() {
        return cAlterarP;
    }

    public JCheckBox getcAlterarU() {
        return cAlterarU;
    }

    public JCheckBox getcCadastrarC() {
        return cCadastrarC;
    }

    public JCheckBox getcCadastrarF() {
        return cCadastrarF;
    }

    public JCheckBox getcCadastrarP() {
        return cCadastrarP;
    }

    public JCheckBox getcCadastrarU() {
        return cCadastrarU;
    }

    public JCheckBox getcCliente() {
        return cCliente;
    }

    public JCheckBox getcDefinirDesconto() {
        return cDefinirDesconto;
    }

    public JCheckBox getcFazerCotacao() {
        return cFazerCotacao;
    }

    public JCheckBox getcFazerPedidos() {
        return cFazerPedidos;
    }

    public JCheckBox getcFazerVendas() {
        return cFazerVendas;
    }

    public JCheckBox getcFornecedor() {
        return cFornecedor;
    }

    public JCheckBox getcProdutos() {
        return cProdutos;
    }

    public JCheckBox getcREntradaP() {
        return cREntradaP;
    }

    public JCheckBox getcREstoque() {
        return cREstoque;
    }

    public JCheckBox getcRPrazo() {
        return cRPrazo;
    }

    public JCheckBox getcRelatorios() {
        return cRelatorios;
    }

    public JCheckBox getcRemoverF() {
        return cRemoverF;
    }

    public JCheckBox getcRemoverP() {
        return cRemoverP;
    }

    public JCheckBox getcRemoverU() {
        return cRemoverU;
    }

    public JCheckBox getcSaidaP() {
        return cSaidaP;
    }

    public JCheckBox getcUsuario() {
        return cUsuario;
    }

    public JCheckBox getcVendas() {
        return cVendas;
    }

    public JCheckBox getCremoverC() {
        return cremoverC;
    }

    public void actualizar(boolean[] per) {
        cAlterarC.setSelected(per[0]);
        cAlterarF.setSelected(per[1]);
        cAlterarP.setSelected(per[2]);
        cAlterarU.setSelected(per[3]);
        cCadastrarC.setSelected(per[4]);
        cCadastrarF.setSelected(per[5]);
        cCadastrarP.setSelected(per[6]);
        cCadastrarU.setSelected(per[7]);
        cCliente.setSelected(per[8]);
        cDefinirDesconto.setSelected(per[9]);
        cFazerCotacao.setSelected(per[10]);
        cFazerPedidos.setSelected(per[11]);
        cFazerVendas.setSelected(per[12]);
        cFornecedor.setSelected(per[13]);
        cProdutos.setSelected(per[14]);
        cREntradaP.setSelected(per[15]);
        cREstoque.setSelected(per[16]);
        cRPrazo.setSelected(per[17]);
        cRelatorios.setSelected(per[18]);
        cRemoverF.setSelected(per[19]);
        cRemoverP.setSelected(per[20]);
        cRemoverU.setSelected(per[21]);
        cSaidaP.setSelected(per[22]);
        cUsuario.setSelected(per[23]);
        cVendas.setSelected(per[24]);
        cremoverC.setSelected(per[25]);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cAlterarC;
    private javax.swing.JCheckBox cAlterarF;
    private javax.swing.JCheckBox cAlterarP;
    private javax.swing.JCheckBox cAlterarU;
    private javax.swing.JCheckBox cCadastrarC;
    private javax.swing.JCheckBox cCadastrarF;
    private javax.swing.JCheckBox cCadastrarP;
    private javax.swing.JCheckBox cCadastrarU;
    private javax.swing.JCheckBox cCliente;
    private javax.swing.JCheckBox cDefinirDesconto;
    private javax.swing.JCheckBox cFazerCotacao;
    private javax.swing.JCheckBox cFazerPedidos;
    private javax.swing.JCheckBox cFazerVendas;
    private javax.swing.JCheckBox cFornecedor;
    private javax.swing.JCheckBox cProdutos;
    private javax.swing.JCheckBox cREntradaP;
    private javax.swing.JCheckBox cREstoque;
    private javax.swing.JCheckBox cRPrazo;
    public static javax.swing.JCheckBox cRelatorios;
    private javax.swing.JCheckBox cRemoverF;
    private javax.swing.JCheckBox cRemoverP;
    private javax.swing.JCheckBox cRemoverU;
    private javax.swing.JCheckBox cSaidaP;
    public static javax.swing.JCheckBox cUsuario;
    public static javax.swing.JCheckBox cVendas;
    private javax.swing.JCheckBox cremoverC;
    // End of variables declaration//GEN-END:variables
}
