package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="clever"
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Endereco endereco;
     private String nomeCliente;
     private String observacao;
     private Integer cell1;
     private Integer cell2;
     private double valorLimiteEmprestimo;
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public Cliente() {
    }

	
    public Cliente(String nomeCliente, double valorLimiteEmprestimo) {
        this.nomeCliente = nomeCliente;
        this.valorLimiteEmprestimo = valorLimiteEmprestimo;
    }
    public Cliente(Endereco endereco, String nomeCliente, String observacao, Integer cell1, Integer cell2, double valorLimiteEmprestimo, Set<Venda> vendas) {
       this.endereco = endereco;
       this.nomeCliente = nomeCliente;
       this.observacao = observacao;
       this.cell1 = cell1;
       this.cell2 = cell2;
       this.valorLimiteEmprestimo = valorLimiteEmprestimo;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_endereco")
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="nome_cliente", nullable=false, length=30)
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }

    
    @Column(name="observacao")
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="cell1")
    public Integer getCell1() {
        return this.cell1;
    }
    
    public void setCell1(Integer cell1) {
        this.cell1 = cell1;
    }

    
    @Column(name="cell2")
    public Integer getCell2() {
        return this.cell2;
    }
    
    public void setCell2(Integer cell2) {
        this.cell2 = cell2;
    }

    
    @Column(name="valor_limite_emprestimo", nullable=false, precision=22, scale=0)
    public double getValorLimiteEmprestimo() {
        return this.valorLimiteEmprestimo;
    }
    
    public void setValorLimiteEmprestimo(double valorLimiteEmprestimo) {
        this.valorLimiteEmprestimo = valorLimiteEmprestimo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


