package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClientePerfil generated by hbm2java
 */
@Entity
@Table(name="cliente_perfil"
    ,catalog="clever"
)
public class ClientePerfil  implements java.io.Serializable {


     private Integer idClientePerfil;
     private boolean cadastrarCliente;
     private boolean excluirCliente;
     private boolean actualizarCliente;
     private boolean telaCliente;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public ClientePerfil() {
    }

	
    public ClientePerfil(boolean cadastrarCliente, boolean excluirCliente, boolean actualizarCliente, boolean telaCliente) {
        this.cadastrarCliente = cadastrarCliente;
        this.excluirCliente = excluirCliente;
        this.actualizarCliente = actualizarCliente;
        this.telaCliente = telaCliente;
    }
    public ClientePerfil(boolean cadastrarCliente, boolean excluirCliente, boolean actualizarCliente, boolean telaCliente, Set<Perfil> perfils) {
       this.cadastrarCliente = cadastrarCliente;
       this.excluirCliente = excluirCliente;
       this.actualizarCliente = actualizarCliente;
       this.telaCliente = telaCliente;
       this.perfils = perfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente_perfil", unique=true, nullable=false)
    public Integer getIdClientePerfil() {
        return this.idClientePerfil;
    }
    
    public void setIdClientePerfil(Integer idClientePerfil) {
        this.idClientePerfil = idClientePerfil;
    }

    
    @Column(name="cadastrar_cliente", nullable=false)
    public boolean isCadastrarCliente() {
        return this.cadastrarCliente;
    }
    
    public void setCadastrarCliente(boolean cadastrarCliente) {
        this.cadastrarCliente = cadastrarCliente;
    }

    
    @Column(name="excluir_cliente", nullable=false)
    public boolean isExcluirCliente() {
        return this.excluirCliente;
    }
    
    public void setExcluirCliente(boolean excluirCliente) {
        this.excluirCliente = excluirCliente;
    }

    
    @Column(name="actualizar_cliente", nullable=false)
    public boolean isActualizarCliente() {
        return this.actualizarCliente;
    }
    
    public void setActualizarCliente(boolean actualizarCliente) {
        this.actualizarCliente = actualizarCliente;
    }

    
    @Column(name="tela_cliente", nullable=false)
    public boolean isTelaCliente() {
        return this.telaCliente;
    }
    
    public void setTelaCliente(boolean telaCliente) {
        this.telaCliente = telaCliente;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="clientePerfil")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


