package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="clever"
)
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private String avenida;
     private String bairro;
     private Integer quarteirao;
     private int numeroCasa;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Endereco() {
    }

	
    public Endereco(String avenida, String bairro, int numeroCasa) {
        this.avenida = avenida;
        this.bairro = bairro;
        this.numeroCasa = numeroCasa;
    }
    public Endereco(String avenida, String bairro, Integer quarteirao, int numeroCasa, Set<Usuario> usuarios, Set<Fornecedor> fornecedors, Set<Cliente> clientes) {
       this.avenida = avenida;
       this.bairro = bairro;
       this.quarteirao = quarteirao;
       this.numeroCasa = numeroCasa;
       this.usuarios = usuarios;
       this.fornecedors = fornecedors;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_endereco", unique=true, nullable=false)
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }

    
    @Column(name="avenida", nullable=false, length=25)
    public String getAvenida() {
        return this.avenida;
    }
    
    public void setAvenida(String avenida) {
        this.avenida = avenida;
    }

    
    @Column(name="bairro", nullable=false, length=25)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="quarteirao")
    public Integer getQuarteirao() {
        return this.quarteirao;
    }
    
    public void setQuarteirao(Integer quarteirao) {
        this.quarteirao = quarteirao;
    }

    
    @Column(name="numero_casa", nullable=false)
    public int getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(int numeroCasa) {
        this.numeroCasa = numeroCasa;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="endereco")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="endereco")
    public Set<Fornecedor> getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set<Fornecedor> fornecedors) {
        this.fornecedors = fornecedors;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="endereco")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


