package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="clever"
)
public class Fornecedor  implements java.io.Serializable {


     private Integer idFornecedor;
     private Endereco endereco;
     private String nomeFornecedor;
     private String email;
     private Integer cell1;
     private Integer cell2;
     private Set<ProdutoFornecedor> produtoFornecedors = new HashSet<ProdutoFornecedor>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(Endereco endereco, String nomeFornecedor) {
        this.endereco = endereco;
        this.nomeFornecedor = nomeFornecedor;
    }
    public Fornecedor(Endereco endereco, String nomeFornecedor, String email, Integer cell1, Integer cell2, Set<ProdutoFornecedor> produtoFornecedors) {
       this.endereco = endereco;
       this.nomeFornecedor = nomeFornecedor;
       this.email = email;
       this.cell1 = cell1;
       this.cell2 = cell2;
       this.produtoFornecedors = produtoFornecedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_fornecedor", unique=true, nullable=false)
    public Integer getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(Integer idFornecedor) {
        this.idFornecedor = idFornecedor;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_endereco", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="nome_fornecedor", nullable=false, length=35)
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }

    
    @Column(name="email", length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="cell1")
    public Integer getCell1() {
        return this.cell1;
    }
    
    public void setCell1(Integer cell1) {
        this.cell1 = cell1;
    }

    
    @Column(name="cell2")
    public Integer getCell2() {
        return this.cell2;
    }
    
    public void setCell2(Integer cell2) {
        this.cell2 = cell2;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="fornecedor")
    public Set<ProdutoFornecedor> getProdutoFornecedors() {
        return this.produtoFornecedors;
    }
    
    public void setProdutoFornecedors(Set<ProdutoFornecedor> produtoFornecedors) {
        this.produtoFornecedors = produtoFornecedors;
    }




}


