package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * ItemVenda generated by hbm2java
 */
@Entity
@Table(name="item_venda"
    ,catalog="clever"
)
public class ItemVenda  implements java.io.Serializable {


     private ItemVendaId id;
     private Produto produto;
     private Venda venda;
     private int quantidade;
     private double subtotal;

    public ItemVenda() {
    }

    public ItemVenda(ItemVendaId id, Produto produto, Venda venda, int quantidade, double subtotal) {
       this.id = id;
       this.produto = produto;
       this.venda = venda;
       this.quantidade = quantidade;
       this.subtotal = subtotal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVenda", column=@Column(name="id_venda", nullable=false) ), 
        @AttributeOverride(name="idProduto", column=@Column(name="id_produto", nullable=false) ) } )
    public ItemVendaId getId() {
        return this.id;
    }
    
    public void setId(ItemVendaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_produto", nullable=false, insertable=false, updatable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_venda", nullable=false, insertable=false, updatable=false)
@Cascade(CascadeType.SAVE_UPDATE)
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="subtotal", nullable=false, precision=22, scale=0)
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }




}


