package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagamentoEmprestimo generated by hbm2java
 */
@Entity
@Table(name="pagamento_emprestimo"
    ,catalog="clever"
)
public class PagamentoEmprestimo  implements java.io.Serializable {


     private Integer idPagamento;
     private Venda venda;
     private Date dataPagamento;
     private double valorPago;
     private double troco;

    public PagamentoEmprestimo() {
    }

    public PagamentoEmprestimo(Venda venda, Date dataPagamento, double valorPago, double troco) {
       this.venda = venda;
       this.dataPagamento = dataPagamento;
       this.valorPago = valorPago;
       this.troco = troco;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pagamento", unique=true, nullable=false)
    public Integer getIdPagamento() {
        return this.idPagamento;
    }
    
    public void setIdPagamento(Integer idPagamento) {
        this.idPagamento = idPagamento;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_venda", nullable=false)
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_pagamento", nullable=false, length=19)
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    
    @Column(name="valor_pago", nullable=false, precision=22, scale=0)
    public double getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(double valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="troco", nullable=false, precision=22, scale=0)
    public double getTroco() {
        return this.troco;
    }
    
    public void setTroco(double troco) {
        this.troco = troco;
    }




}


