package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="perfil"
    ,catalog="clever"
)
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private ClientePerfil clientePerfil;
     private FornecedorPerfil fornecedorPerfil;
     private ProdutoPerfil produtoPerfil;
     private RelatorioPerfil relatorioPerfil;
     private UsuarioPerfil usuarioPerfil;
     private VendasPerfil vendasPerfil;
     private String perfilNome;
     private boolean perfilTela;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfil() {
    }

	
    public Perfil(ClientePerfil clientePerfil, FornecedorPerfil fornecedorPerfil, ProdutoPerfil produtoPerfil, RelatorioPerfil relatorioPerfil, UsuarioPerfil usuarioPerfil, VendasPerfil vendasPerfil, String perfilNome, boolean perfilTela) {
        this.clientePerfil = clientePerfil;
        this.fornecedorPerfil = fornecedorPerfil;
        this.produtoPerfil = produtoPerfil;
        this.relatorioPerfil = relatorioPerfil;
        this.usuarioPerfil = usuarioPerfil;
        this.vendasPerfil = vendasPerfil;
        this.perfilNome = perfilNome;
        this.perfilTela = perfilTela;
    }
    public Perfil(ClientePerfil clientePerfil, FornecedorPerfil fornecedorPerfil, ProdutoPerfil produtoPerfil, RelatorioPerfil relatorioPerfil, UsuarioPerfil usuarioPerfil, VendasPerfil vendasPerfil, String perfilNome, boolean perfilTela, Set<Usuario> usuarios) {
       this.clientePerfil = clientePerfil;
       this.fornecedorPerfil = fornecedorPerfil;
       this.produtoPerfil = produtoPerfil;
       this.relatorioPerfil = relatorioPerfil;
       this.usuarioPerfil = usuarioPerfil;
       this.vendasPerfil = vendasPerfil;
       this.perfilNome = perfilNome;
       this.perfilTela = perfilTela;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_perfil", unique=true, nullable=false)
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_cliente_perfil", nullable=false)
    public ClientePerfil getClientePerfil() {
        return this.clientePerfil;
    }
    
    public void setClientePerfil(ClientePerfil clientePerfil) {
        this.clientePerfil = clientePerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_fornecedor_perfil", nullable=false)
    public FornecedorPerfil getFornecedorPerfil() {
        return this.fornecedorPerfil;
    }
    
    public void setFornecedorPerfil(FornecedorPerfil fornecedorPerfil) {
        this.fornecedorPerfil = fornecedorPerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_produto_perfil", nullable=false)
    public ProdutoPerfil getProdutoPerfil() {
        return this.produtoPerfil;
    }
    
    public void setProdutoPerfil(ProdutoPerfil produtoPerfil) {
        this.produtoPerfil = produtoPerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_relatorio_perfil", nullable=false)
    public RelatorioPerfil getRelatorioPerfil() {
        return this.relatorioPerfil;
    }
    
    public void setRelatorioPerfil(RelatorioPerfil relatorioPerfil) {
        this.relatorioPerfil = relatorioPerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_usuario_perfil", nullable=false)
    public UsuarioPerfil getUsuarioPerfil() {
        return this.usuarioPerfil;
    }
    
    public void setUsuarioPerfil(UsuarioPerfil usuarioPerfil) {
        this.usuarioPerfil = usuarioPerfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_vendas_perfil", nullable=false)
    public VendasPerfil getVendasPerfil() {
        return this.vendasPerfil;
    }
    
    public void setVendasPerfil(VendasPerfil vendasPerfil) {
        this.vendasPerfil = vendasPerfil;
    }

    
    @Column(name="perfil_nome", nullable=false, length=45)
    public String getPerfilNome() {
        return this.perfilNome;
    }
    
    public void setPerfilNome(String perfilNome) {
        this.perfilNome = perfilNome;
    }

    
    @Column(name="perfil_tela", nullable=false)
    public boolean isPerfilTela() {
        return this.perfilTela;
    }
    
    public void setPerfilTela(boolean perfilTela) {
        this.perfilTela = perfilTela;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perfil")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


