package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoPerfil generated by hbm2java
 */
@Entity
@Table(name="produto_perfil"
    ,catalog="clever"
)
public class ProdutoPerfil  implements java.io.Serializable {


     private Integer idProdutoPerfil;
     private boolean cadastrarProduto;
     private boolean excluirProduto;
     private boolean actualizarProduto;
     private boolean telaProduto;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public ProdutoPerfil() {
    }

	
    public ProdutoPerfil(boolean cadastrarProduto, boolean excluirProduto, boolean actualizarProduto, boolean telaProduto) {
        this.cadastrarProduto = cadastrarProduto;
        this.excluirProduto = excluirProduto;
        this.actualizarProduto = actualizarProduto;
        this.telaProduto = telaProduto;
    }
    public ProdutoPerfil(boolean cadastrarProduto, boolean excluirProduto, boolean actualizarProduto, boolean telaProduto, Set<Perfil> perfils) {
       this.cadastrarProduto = cadastrarProduto;
       this.excluirProduto = excluirProduto;
       this.actualizarProduto = actualizarProduto;
       this.telaProduto = telaProduto;
       this.perfils = perfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produto_perfil", unique=true, nullable=false)
    public Integer getIdProdutoPerfil() {
        return this.idProdutoPerfil;
    }
    
    public void setIdProdutoPerfil(Integer idProdutoPerfil) {
        this.idProdutoPerfil = idProdutoPerfil;
    }

    
    @Column(name="cadastrar_produto", nullable=false)
    public boolean isCadastrarProduto() {
        return this.cadastrarProduto;
    }
    
    public void setCadastrarProduto(boolean cadastrarProduto) {
        this.cadastrarProduto = cadastrarProduto;
    }

    
    @Column(name="excluir_produto", nullable=false)
    public boolean isExcluirProduto() {
        return this.excluirProduto;
    }
    
    public void setExcluirProduto(boolean excluirProduto) {
        this.excluirProduto = excluirProduto;
    }

    
    @Column(name="actualizar_produto", nullable=false)
    public boolean isActualizarProduto() {
        return this.actualizarProduto;
    }
    
    public void setActualizarProduto(boolean actualizarProduto) {
        this.actualizarProduto = actualizarProduto;
    }

    
    @Column(name="tela_produto", nullable=false)
    public boolean isTelaProduto() {
        return this.telaProduto;
    }
    
    public void setTelaProduto(boolean telaProduto) {
        this.telaProduto = telaProduto;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="produtoPerfil")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


