package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProdutoFornecedor generated by hbm2java
 */
@Entity
@Table(name="produto_fornecedor"
    ,catalog="clever"
)
public class ProdutoFornecedor  implements java.io.Serializable {


     private int idProduto;
     private Fornecedor fornecedor;
     private Produto produto;
     private String auxiliar;

    public ProdutoFornecedor() {
    }

	
    public ProdutoFornecedor(Produto produto) {
        this.produto = produto;
    }
    public ProdutoFornecedor(Fornecedor fornecedor, Produto produto, String auxiliar) {
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.auxiliar = auxiliar;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="produto"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_produto", unique=true, nullable=false)
 
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)

    @JoinColumn(name="id_fornecedor")
@Cascade(CascadeType.SAVE_UPDATE)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
@Cascade(CascadeType.SAVE_UPDATE)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="auxiliar", length=45)
    public String getAuxiliar() {
        return this.auxiliar;
    }
    
    public void setAuxiliar(String auxiliar) {
        this.auxiliar = auxiliar;
    }




}


