package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RelatorioPerfil generated by hbm2java
 */
@Entity
@Table(name="relatorio_perfil"
    ,catalog="clever"
)
public class RelatorioPerfil  implements java.io.Serializable {


     private Integer idRelatorioPerfil;
     private boolean acederRentrada;
     private boolean acederRsaida;
     private boolean acederRestoque;
     private boolean abaixoPrazo;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public RelatorioPerfil() {
    }

	
    public RelatorioPerfil(boolean acederRentrada, boolean acederRsaida, boolean acederRestoque, boolean abaixoPrazo) {
        this.acederRentrada = acederRentrada;
        this.acederRsaida = acederRsaida;
        this.acederRestoque = acederRestoque;
        this.abaixoPrazo = abaixoPrazo;
    }
    public RelatorioPerfil(boolean acederRentrada, boolean acederRsaida, boolean acederRestoque, boolean abaixoPrazo, Set<Perfil> perfils) {
       this.acederRentrada = acederRentrada;
       this.acederRsaida = acederRsaida;
       this.acederRestoque = acederRestoque;
       this.abaixoPrazo = abaixoPrazo;
       this.perfils = perfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_relatorio_perfil", unique=true, nullable=false)
    public Integer getIdRelatorioPerfil() {
        return this.idRelatorioPerfil;
    }
    
    public void setIdRelatorioPerfil(Integer idRelatorioPerfil) {
        this.idRelatorioPerfil = idRelatorioPerfil;
    }

    
    @Column(name="acederREntrada", nullable=false)
    public boolean isAcederRentrada() {
        return this.acederRentrada;
    }
    
    public void setAcederRentrada(boolean acederRentrada) {
        this.acederRentrada = acederRentrada;
    }

    
    @Column(name="acederRSaida", nullable=false)
    public boolean isAcederRsaida() {
        return this.acederRsaida;
    }
    
    public void setAcederRsaida(boolean acederRsaida) {
        this.acederRsaida = acederRsaida;
    }

    
    @Column(name="acederREstoque", nullable=false)
    public boolean isAcederRestoque() {
        return this.acederRestoque;
    }
    
    public void setAcederRestoque(boolean acederRestoque) {
        this.acederRestoque = acederRestoque;
    }

    
    @Column(name="abaixo_prazo", nullable=false)
    public boolean isAbaixoPrazo() {
        return this.abaixoPrazo;
    }
    
    public void setAbaixoPrazo(boolean abaixoPrazo) {
        this.abaixoPrazo = abaixoPrazo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="relatorioPerfil")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


