package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tipoproduto generated by hbm2java
 */
@Entity
@Table(name="tipoproduto"
    ,catalog="clever"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome_tipo") 
)
public class Tipoproduto  implements java.io.Serializable {


     private Integer idTipoProduto;
     private String nomeTipo;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Tipoproduto() {
    }

	
    public Tipoproduto(String nomeTipo) {
        this.nomeTipo = nomeTipo;
    }
    public Tipoproduto(String nomeTipo, Set<Produto> produtos) {
       this.nomeTipo = nomeTipo;
       this.produtos = produtos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipoProduto", unique=true, nullable=false)
    public Integer getIdTipoProduto() {
        return this.idTipoProduto;
    }
    
    public void setIdTipoProduto(Integer idTipoProduto) {
        this.idTipoProduto = idTipoProduto;
    }

    
    @Column(name="nome_tipo", unique=true, nullable=false, length=20)
    public String getNomeTipo() {
        return this.nomeTipo;
    }
    
    public void setNomeTipo(String nomeTipo) {
        this.nomeTipo = nomeTipo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="tipoproduto")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


