package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="clever"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Endereco endereco;
     private Perfil perfil;
     private String nomeUsuario;
     private String sexoUsuario;
     private byte[] imagem;
     private String username;
     private String senha;
     private Integer cell1;
     private Integer cell2;
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public Usuario() {
    }

	
    public Usuario(Endereco endereco, Perfil perfil, String nomeUsuario, String sexoUsuario, byte[] imagem, String username, String senha) {
        this.endereco = endereco;
        this.perfil = perfil;
        this.nomeUsuario = nomeUsuario;
        this.sexoUsuario = sexoUsuario;
        this.imagem = imagem;
        this.username = username;
        this.senha = senha;
    }
    public Usuario(Endereco endereco, Perfil perfil, String nomeUsuario, String sexoUsuario, byte[] imagem, String username, String senha, Integer cell1, Integer cell2, Set<Venda> vendas) {
       this.endereco = endereco;
       this.perfil = perfil;
       this.nomeUsuario = nomeUsuario;
       this.sexoUsuario = sexoUsuario;
       this.imagem = imagem;
       this.username = username;
       this.senha = senha;
       this.cell1 = cell1;
       this.cell2 = cell2;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_endereco", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_perfil", nullable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="nome_usuario", nullable=false, length=30)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    
    @Column(name="sexo_usuario", nullable=false, length=15)
    public String getSexoUsuario() {
        return this.sexoUsuario;
    }
    
    public void setSexoUsuario(String sexoUsuario) {
        this.sexoUsuario = sexoUsuario;
    }

    
    @Column(name="imagem", nullable=false)
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }

    
    @Column(name="username", nullable=false, length=15)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="senha", nullable=false, length=10)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="cell1")
    public Integer getCell1() {
        return this.cell1;
    }
    
    public void setCell1(Integer cell1) {
        this.cell1 = cell1;
    }

    
    @Column(name="cell2")
    public Integer getCell2() {
        return this.cell2;
    }
    
    public void setCell2(Integer cell2) {
        this.cell2 = cell2;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="usuario")
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


