package Modelo;
// Generated Nov 1, 2015 5:59:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name="usuario_perfil"
    ,catalog="clever"
)
public class UsuarioPerfil  implements java.io.Serializable {


     private Integer idUsuarioPerfil;
     private boolean cadastrarUsuario;
     private boolean excluirUsuario;
     private boolean actualizarUsuario;
     private boolean telaUsuario;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public UsuarioPerfil() {
    }

	
    public UsuarioPerfil(boolean cadastrarUsuario, boolean excluirUsuario, boolean actualizarUsuario, boolean telaUsuario) {
        this.cadastrarUsuario = cadastrarUsuario;
        this.excluirUsuario = excluirUsuario;
        this.actualizarUsuario = actualizarUsuario;
        this.telaUsuario = telaUsuario;
    }
    public UsuarioPerfil(boolean cadastrarUsuario, boolean excluirUsuario, boolean actualizarUsuario, boolean telaUsuario, Set<Perfil> perfils) {
       this.cadastrarUsuario = cadastrarUsuario;
       this.excluirUsuario = excluirUsuario;
       this.actualizarUsuario = actualizarUsuario;
       this.telaUsuario = telaUsuario;
       this.perfils = perfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario_perfil", unique=true, nullable=false)
    public Integer getIdUsuarioPerfil() {
        return this.idUsuarioPerfil;
    }
    
    public void setIdUsuarioPerfil(Integer idUsuarioPerfil) {
        this.idUsuarioPerfil = idUsuarioPerfil;
    }

    
    @Column(name="cadastrar_usuario", nullable=false)
    public boolean isCadastrarUsuario() {
        return this.cadastrarUsuario;
    }
    
    public void setCadastrarUsuario(boolean cadastrarUsuario) {
        this.cadastrarUsuario = cadastrarUsuario;
    }

    
    @Column(name="excluir_usuario", nullable=false)
    public boolean isExcluirUsuario() {
        return this.excluirUsuario;
    }
    
    public void setExcluirUsuario(boolean excluirUsuario) {
        this.excluirUsuario = excluirUsuario;
    }

    
    @Column(name="actualizar_usuario", nullable=false)
    public boolean isActualizarUsuario() {
        return this.actualizarUsuario;
    }
    
    public void setActualizarUsuario(boolean actualizarUsuario) {
        this.actualizarUsuario = actualizarUsuario;
    }

    
    @Column(name="tela_usuario", nullable=false)
    public boolean isTelaUsuario() {
        return this.telaUsuario;
    }
    
    public void setTelaUsuario(boolean telaUsuario) {
        this.telaUsuario = telaUsuario;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="usuarioPerfil")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


